planta(diente_leon).
planta(manzanilla).
planta(abrojo).
planta(acacia).
planta(acanto).
planta(aceitilla).
planta(achicoria).
planta(malva).
planta(zarzaparrila).
planta(anis).
planta(perejil).
planta(sanguinaria).
planta(limon).
planta(sauco).
planta(arnica).
planta(llanten).
planta(fenogreco).
planta(zarzamora).
planta(salvia).
planta(tilo).
planta(valeriana).
planta(yerbabuena).
planta(jugo_limon).
planta(jugo_toronja).
planta(pingüica).
planta(quina_roja).
planta(encino_rojo).
planta(pimiento).
planta(hamamelis).
planta(cola_caballo).
planta(toques).
planta(ajenjo).
planta(germen_trigo).
planta(quina).
planta(canela).
planta(halholva).
planta(eucalipto).
planta(cebada).
planta(tabachin).
planta(borroja).
planta(gerciana).
planta(cardo).
planta(zarzaparrilla).
planta(chicalote).
planta(alcanfor).
planta(toronja).
planta(marrubio).
planta(toloache).
planta(oregano).
planta(lupulo).
planta(cuasia).
planta(uva).
planta(cerezo).
planta(rosal).
planta(borraja).
planta(anacahuite).
planta(gordolobo).
planta(benjui).
planta(rabano).
planta(cordolobo).
planta(ipecacuana).
planta(mostaza).
planta(ortiga).
planta(espinosilla).
planta(romero).
planta(tila).
planta(aceite_oliva).
planta(retoma).
planta(cabellos_elote).
planta(pingüice).
planta(ajo).
planta(cebolla).
planta(hiedra).
planta(chuachalalate).
planta(siempreviva).
planta(mastuerzo).
planta(higuera).
planta(toronjil).
planta(doradilla).
planta(menta).
planta(hinojo).
planta(boido).
planta(linoza).
planta(laurel).
planta(brionia).
planta(digital).
planta(nuez_kcla).
planta(tejocote).
planta(uchicoria).
planta(apio).
planta(sanguinara).
planta(berro).
planta(matarique).
planta(tronadora).
planta(damiana).
planta(capulin).
planta(mezquite_corteza).
planta(tlachichinole).
planta(linaza).
planta(membtrillo).
planta(arroz).
planta(guayaba).
planta(albahaca).
planta(granada).
planta(simonillo).
planta(sirmpretiva).
planta(chaparro_amargoso).
planta(muicle).
planta(monacillo).
planta(naranja).
planta(tamarindo).
planta(ipecacuiame).
planta(cedral).
planta(amis).
planta(genciana).
planta(tabaquillo).
planta(ruibardo).
planta(anis_estrella).
planta(cedron).
planta(hierba_pollo).
planta(zanahoria).
planta(gexanio).
planta(ciruela).
planta(chia).
planta(agar).
planta(larenda).
planta(tomillo).
planta(amis_estrella).
planta(toronjill).
planta(ruida).
planta(alfalfa).
planta(lino).
planta(malvavisco).
planta(pino).
planta(aconito).
planta(belladora).
planta(beleño).
planta(colchito).
planta(encina).
planta(nogal).
planta(milenrana).
planta(calendula).
planta(retama).
planta(boldo).
planta(alcachofa).
planta(prodigiosa).
planta(cascara_sagrada).
planta(helecho).
planta(ricino).
planta(tabaco).
planta(benos).
planta(marubio).
planta(ruibarbo).
planta(lechuga).
planta(papoloquelite).
planta(berros).
planta(llanton).
planta(tecomasuchil).
planta(esparrago).
planta(alpiste).
planta(muerdago).
planta(miel).
planta(nuez_kola).
planta(crategus).
planta(acadera).
planta(azahar).
planta(gelsenio).
planta(tita).
planta(pasiflora).
planta(melisa).
planta(yohimbo).
planta(domiana).
planta(nuez_vomica).
planta(aguacate).
planta(acomito).
planta(rosa).
planta(encino).
planta(zarzaparilla).
planta(enebro).
planta(betonia).
planta(papaya).
planta(epazote).
planta(avena).
planta(verbena).
planta(girasol).
planta(azfran).
planta(belladona).
planta(ruda).
planta(hisopo).
planta(quina_amarilla).
planta(sabina).
planta(artemisa).
planta(zapatle).
planta(cuerecillo_centeno).
planta(clavo).
planta(salvio).
planta(manzanillo).
planta(te_negro).
planta(mate).
planta(grame).
planta(torongil).
planta(puerro).
planta(fresno).
planta(anagolida).
planta(jengibre).
planta(ipecacuama).
planta(ocote).
planta(gobernadora).
planta(cola_cebolla).
planta(estafiate).
planta(pirul).
planta(semilla_calabaza).
planta(coquito_aceite).
planta(raiz_granada_agria).
planta(helecho_macho).
planta(gelsemio).
planta(violeta).
planta(jugo_vastago_platano_morado).
planta(roble).
planta(cuachalalate).
planta(castaño_indias).
planta(cipres).
planta(leche_higuera).
planta(espino).
planta(cilantro).
planta(espinacas).
planta(acelga).
planta(aceite_bacalao).
planta(cempasuchi).