module Main where

import Test.Tasty
import Test.Tasty.HUnit
import FizzBuzz

fizzBuzzSuite :: TestTree
fizzBuzzSuite = testGroup "FizzBuzz tests"
    [ testGroup "Grupo 1"
        [ testCase "0" $ fizzbuzz 0 @?= "cero"
        , testCase "1" $ fizzbuzz 1 @?= "uno"
        , testCase "2" $ fizzbuzz 2 @?= "FizzBuzz!"
        , testCase "3" $ fizzbuzz 3 @?= "FizzBuzz!"
        , testCase "4" $ fizzbuzz 4 @?= "cuatro"
        , testCase "5" $ fizzbuzz 5 @?= "FizzBuzz!"
        , testCase "6" $ fizzbuzz 6 @?= "seis"
        , testCase "7" $ fizzbuzz 7 @?= "FizzBuzz!"
        , testCase "8" $ fizzbuzz 8 @?= "ocho"
        , testCase "9" $ fizzbuzz 9 @?= "nueve"
        , testCase "10" $ fizzbuzz 10 @?= "diez"
        , testCase "11" $ fizzbuzz 11 @?= "FizzBuzz!"
        , testCase "12" $ fizzbuzz 12 @?= "doce"
        , testCase "13" $ fizzbuzz 13 @?= "FizzBuzz!"
        , testCase "14" $ fizzbuzz 14 @?= "catorce"
        , testCase "15" $ fizzbuzz 15 @?= "quince"
        , testCase "20" $ fizzbuzz 20 @?= "veinte"
        , testCase "30" $ fizzbuzz 30 @?= "treinta"
        ]
    , testGroup "Grupo 2"
        [ testCase "16" $ fizzbuzz 16 @?= "dieciseis"
        , testCase "17" $ fizzbuzz 17 @?= "FizzBuzz!"
        , testCase "18" $ fizzbuzz 18 @?= "dieciocho"
        , testCase "19" $ fizzbuzz 19 @?= "FizzBuzz!"
        , testCase "20" $ fizzbuzz 20 @?= "veinte"
        , testCase "21" $ fizzbuzz 21 @?= "veintiuno"
        , testCase "22" $ fizzbuzz 22 @?= "veintidos"
        , testCase "23" $ fizzbuzz 23 @?= "FizzBuzz!"
        , testCase "24" $ fizzbuzz 24 @?= "veinticuatro"
        , testCase "25" $ fizzbuzz 25 @?= "veinticinco"
        , testCase "26" $ fizzbuzz 26 @?= "veintiseis"
        , testCase "27" $ fizzbuzz 27 @?= "veintisiete"
        , testCase "28" $ fizzbuzz 28 @?= "veintiocho"
        , testCase "29" $ fizzbuzz 29 @?= "FizzBuzz!"
        ]
    , testGroup "Grupo 3"
        [ testCase "30" $ fizzbuzz 30 @?= "treinta"
        , testCase "31" $ fizzbuzz 31 @?= "FizzBuzz!"
        , testCase "32" $ fizzbuzz 32 @?= "treinta y dos"
        , testCase "37" $ fizzbuzz 37 @?= "FizzBuzz!"
        , testCase "39" $ fizzbuzz 39 @?= "treinta y nueve"
        , testCase "41" $ fizzbuzz 41 @?= "FizzBuzz!"
        , testCase "42" $ fizzbuzz 42 @?= "cuarenta y dos"
        , testCase "43" $ fizzbuzz 43 @?= "FizzBuzz!"
        , testCase "47" $ fizzbuzz 47 @?= "FizzBuzz!"
        , testCase "48" $ fizzbuzz 48 @?= "cuarenta y ocho"
        , testCase "51" $ fizzbuzz 51 @?= "cincuenta y uno"
        , testCase "53" $ fizzbuzz 53 @?= "FizzBuzz!"
        , testCase "57" $ fizzbuzz 57 @?= "cincuenta y siete"
        , testCase "58" $ fizzbuzz 58 @?= "cincuenta y ocho"
        , testCase "59" $ fizzbuzz 59 @?= "FizzBuzz!"
        , testCase "60" $ fizzbuzz 60 @?= "sesenta"
        , testCase "61" $ fizzbuzz 61 @?= "FizzBuzz!"
        , testCase "66" $ fizzbuzz 66 @?= "sesenta y seis"
        , testCase "67" $ fizzbuzz 67 @?= "FizzBuzz!"
        , testCase "72" $ fizzbuzz 72 @?= "setenta y dos"
        , testCase "73" $ fizzbuzz 73 @?= "FizzBuzz!"
        , testCase "74" $ fizzbuzz 74 @?= "setenta y cuatro"
        , testCase "75" $ fizzbuzz 75 @?= "setenta y cinco"
        , testCase "82" $ fizzbuzz 82 @?= "ochenta y dos"
        , testCase "83" $ fizzbuzz 83 @?= "FizzBuzz!"
        , testCase "84" $ fizzbuzz 84 @?= "ochenta y cuatro"
        , testCase "89" $ fizzbuzz 89 @?= "FizzBuzz!"
        , testCase "90" $ fizzbuzz 90 @?= "noventa"
        , testCase "91" $ fizzbuzz 91 @?= "noventa y uno"
        , testCase "97" $ fizzbuzz 97 @?= "FizzBuzz!"
        , testCase "98" $ fizzbuzz 98 @?= "noventa y ocho"
        , testCase "99" $ fizzbuzz 99 @?= "noventa y nueve"
        , testCase "100" $ fizzbuzz 100 @?= "cien"
        ]
    ,testGroup "Grupo 4"
        [ testCase "101" $ fizzbuzz 101 @?= "FizzBuzz!"
        , testCase "200" $ fizzbuzz 200 @?= "doscientos"
        , testCase "307" $ fizzbuzz 307 @?= "FizzBuzz!"
        , testCase "450" $ fizzbuzz 450 @?= "cuatrocientos cincuenta"
        , testCase "503" $ fizzbuzz 503 @?= "FizzBuzz!"
        , testCase "600" $ fizzbuzz 600 @?= "seiscientos"
        , testCase "709" $ fizzbuzz 709 @?= "FizzBuzz!"
        , testCase "800" $ fizzbuzz 800 @?= "ochocientos"
        , testCase "857" $ fizzbuzz 857 @?= "FizzBuzz!"
        , testCase "999" $ fizzbuzz 999 @?= "novecientos noventa y nueve"
        ]
    ,testGroup "Grupo 5"
        [ testCase "1001" $ fizzbuzz 1001 @?= "mil uno"
        , testCase "2000" $ fizzbuzz 2000 @?= "dos mil"
        , testCase "3071" $ fizzbuzz 3071 @?= "tres mil setenta y uno"
        , testCase "4500" $ fizzbuzz 4500 @?= "cuatro mil quinientos"
        , testCase "5032" $ fizzbuzz 5032 @?= "cinco mil treinta y dos"
        , testCase "6003" $ fizzbuzz 6003 @?= "seis mil tres"
        , testCase "7096" $ fizzbuzz 7096 @?= "siete mil noventa y seis"
        , testCase "8009" $ fizzbuzz 8009 @?= "FizzBuzz!"
        , testCase "8575" $ fizzbuzz 8575 @?= "ocho mil quinientos setenta y cinco"
        , testCase "9999" $ fizzbuzz 9999 @?= "nueve mil novecientos noventa y nueve"
        ]
    , testGroup "Grupo 6"
        [ testCase "1000001" $ fizzbuzz 1000001 @?= "FizzBuzz!"
        , testCase "1001000" $ fizzbuzz 1001000 @?= "un millón mil"
        , testCase "1003007" $ fizzbuzz 1003007 @?= "un millón tres mil siete"
        , testCase "1004500" $ fizzbuzz 1004500 @?= "un millón cuatro mil quinientos"
        , testCase "1005032" $ fizzbuzz 1005032 @?= "un millón cinco mil treinta y dos"
        ]
    ]
main = defaultMain fizzBuzzSuite
